-- Minimal Tech Atlas Database Setup
-- Only adds missing pieces to existing database

-- Add missing columns to users table if they don't exist
DO $$ BEGIN
    ALTER TABLE "users" ADD COLUMN "categories" json;
EXCEPTION
    WHEN duplicate_column THEN null;
END $$;

-- Create missing tables only if they don't exist

-- Events table (this is the main one causing issues)
CREATE TABLE IF NOT EXISTS "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"type" varchar(100),
	"category" varchar(100),
	"startDate" timestamp NOT NULL,
	"endDate" timestamp,
	"location" varchar(255),
	"address" text,
	"latitude" varchar(50),
	"longitude" varchar(50),
	"virtual" boolean DEFAULT false NOT NULL,
	"meetingUrl" varchar(500),
	"registrationUrl" varchar(500),
	"organizer" varchar(255),
	"organizerEmail" varchar(320),
	"capacity" integer,
	"tags" json,
	"featured" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

-- Jobs table
CREATE TABLE IF NOT EXISTS "jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"company" varchar(255) NOT NULL,
	"description" text,
	"requirements" text,
	"responsibilities" text,
	"type" varchar(20) NOT NULL,
	"location" varchar(255),
	"remote" boolean DEFAULT false NOT NULL,
	"skills" json,
	"experienceLevel" varchar(100),
	"salaryMin" integer,
	"salaryMax" integer,
	"currency" varchar(10) DEFAULT 'UGX',
	"applicationUrl" varchar(500),
	"applicationEmail" varchar(320),
	"featured" boolean DEFAULT false NOT NULL,
	"expiresAt" timestamp,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

-- Opportunities table
CREATE TABLE IF NOT EXISTS "opportunities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"type" varchar(100),
	"provider" varchar(255),
	"amount" varchar(100),
	"currency" varchar(10),
	"eligibility" text,
	"applicationUrl" varchar(500),
	"deadline" timestamp,
	"tags" json,
	"featured" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

-- Hubs table
CREATE TABLE IF NOT EXISTS "hubs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"focusAreas" json,
	"location" varchar(255),
	"address" text,
	"latitude" varchar(50),
	"longitude" varchar(50),
	"email" varchar(320),
	"phone" varchar(50),
	"website" varchar(500),
	"logo" varchar(500),
	"verified" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

-- Communities table
CREATE TABLE IF NOT EXISTS "communities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"focusAreas" json,
	"type" varchar(100),
	"location" varchar(255),
	"memberCount" integer,
	"email" varchar(320),
	"website" varchar(500),
	"slack" varchar(500),
	"discord" varchar(500),
	"telegram" varchar(500),
	"twitter" varchar(255),
	"logo" varchar(500),
	"verified" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

-- Startups table
CREATE TABLE IF NOT EXISTS "startups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"industry" varchar(100),
	"focusAreas" json,
	"stage" varchar(100),
	"founded" integer,
	"location" varchar(255),
	"latitude" varchar(50),
	"longitude" varchar(50),
	"teamSize" integer,
	"email" varchar(320),
	"website" varchar(500),
	"twitter" varchar(255),
	"linkedin" varchar(255),
	"logo" varchar(500),
	"verified" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

-- Forum tables
CREATE TABLE IF NOT EXISTS "forum_threads" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(500) NOT NULL,
	"slug" varchar(500) NOT NULL,
	"content" text NOT NULL,
	"category" varchar(20) DEFAULT 'general' NOT NULL,
	"authorId" integer,
	"authorName" varchar(255),
	"isPinned" boolean DEFAULT false NOT NULL,
	"isLocked" boolean DEFAULT false NOT NULL,
	"viewCount" integer DEFAULT 0 NOT NULL,
	"replyCount" integer DEFAULT 0 NOT NULL,
	"upvotes" integer DEFAULT 0 NOT NULL,
	"downvotes" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastActivityAt" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "forum_replies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"threadId" integer NOT NULL,
	"content" text NOT NULL,
	"authorId" integer,
	"authorName" varchar(255),
	"parentReplyId" integer,
	"upvotes" integer DEFAULT 0 NOT NULL,
	"downvotes" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);

-- Grant admin access to udatalabs@gmail.com
UPDATE users SET role = 'admin' WHERE email = 'udatalabs@gmail.com';

-- Insert admin user if doesn't exist
INSERT INTO users ("openId", name, email, role, "loginMethod", "createdAt", "updatedAt", "lastSignedIn")
VALUES ('udatalabs-admin', 'UData Labs Admin', 'udatalabs@gmail.com', 'admin', 'supabase', NOW(), NOW(), NOW())
ON CONFLICT ("openId") DO UPDATE SET role = 'admin';

-- Success message
SELECT 'Minimal database setup completed! Ready to test event submissions.' as message;