-- Tech Atlas Database Setup for Supabase (Safe Version)
-- This version handles existing types and tables gracefully
-- Run this script in your Supabase SQL Editor

-- Create ENUM types (only if they don't exist)
DO $$ BEGIN
    CREATE TYPE "role" AS ENUM ('user', 'admin', 'moderator', 'editor');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "blog_status" AS ENUM ('draft', 'pending', 'approved', 'rejected', 'published');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "community_status" AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "event_status" AS ENUM ('pending', 'approved', 'rejected', 'completed');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "vote_target" AS ENUM ('thread', 'reply');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "vote_type" AS ENUM ('up', 'down');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "gig_status" AS ENUM ('pending', 'approved', 'rejected', 'completed', 'expired');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "hub_status" AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "job_type" AS ENUM ('full-time', 'part-time', 'internship', 'contract');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "job_status" AS ENUM ('pending', 'approved', 'rejected', 'expired');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "resource_status" AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "opportunity_status" AS ENUM ('pending', 'approved', 'rejected', 'expired');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "startup_status" AS ENUM ('pending', 'approved', 'rejected');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "thread_category" AS ENUM ('general', 'jobs', 'events', 'help', 'showcase', 'feedback');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create users table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" "role" DEFAULT 'user' NOT NULL,
	"bio" text,
	"skills" json,
	"categories" json,
	"location" varchar(255),
	"website" varchar(500),
	"github" varchar(255),
	"twitter" varchar(255),
	"linkedin" varchar(255),
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL
);

-- Add unique constraint if it doesn't exist
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'users_openId_unique' 
        AND table_name = 'users'
    ) THEN
        ALTER TABLE "users" ADD CONSTRAINT "users_openId_unique" UNIQUE("openId");
    END IF;
END $$;

-- Create hubs table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "hubs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"focusAreas" json,
	"location" varchar(255),
	"address" text,
	"latitude" varchar(50),
	"longitude" varchar(50),
	"email" varchar(320),
	"phone" varchar(50),
	"website" varchar(500),
	"logo" varchar(500),
	"verified" boolean DEFAULT false NOT NULL,
	"status" "hub_status" DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'hubs_slug_unique' 
        AND table_name = 'hubs'
    ) THEN
        ALTER TABLE "hubs" ADD CONSTRAINT "hubs_slug_unique" UNIQUE("slug");
    END IF;
END $$;

-- Create communities table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "communities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"focusAreas" json,
	"type" varchar(100),
	"location" varchar(255),
	"memberCount" integer,
	"email" varchar(320),
	"website" varchar(500),
	"slack" varchar(500),
	"discord" varchar(500),
	"telegram" varchar(500),
	"twitter" varchar(255),
	"logo" varchar(500),
	"verified" boolean DEFAULT false NOT NULL,
	"status" "community_status" DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'communities_slug_unique' 
        AND table_name = 'communities'
    ) THEN
        ALTER TABLE "communities" ADD CONSTRAINT "communities_slug_unique" UNIQUE("slug");
    END IF;
END $$;

-- Create startups table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "startups" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"industry" varchar(100),
	"focusAreas" json,
	"stage" varchar(100),
	"founded" integer,
	"location" varchar(255),
	"latitude" varchar(50),
	"longitude" varchar(50),
	"teamSize" integer,
	"email" varchar(320),
	"website" varchar(500),
	"twitter" varchar(255),
	"linkedin" varchar(255),
	"logo" varchar(500),
	"verified" boolean DEFAULT false NOT NULL,
	"status" "startup_status" DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    ALTER TABLE "startups" ADD CONSTRAINT "startups_slug_unique" UNIQUE("slug");
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create jobs table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "jobs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"company" varchar(255) NOT NULL,
	"description" text,
	"requirements" text,
	"responsibilities" text,
	"type" "job_type" NOT NULL,
	"location" varchar(255),
	"remote" boolean DEFAULT false NOT NULL,
	"skills" json,
	"experienceLevel" varchar(100),
	"salaryMin" integer,
	"salaryMax" integer,
	"currency" varchar(10) DEFAULT 'UGX',
	"applicationUrl" varchar(500),
	"applicationEmail" varchar(320),
	"featured" boolean DEFAULT false NOT NULL,
	"expiresAt" timestamp,
	"status" "job_status" DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    ALTER TABLE "jobs" ADD CONSTRAINT "jobs_slug_unique" UNIQUE("slug");
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create gigs table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "gigs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"requirements" text,
	"category" varchar(100),
	"budget" integer,
	"currency" varchar(10) DEFAULT 'UGX',
	"duration" varchar(100),
	"skills" json,
	"remote" boolean DEFAULT true NOT NULL,
	"location" varchar(255),
	"contactEmail" varchar(320),
	"contactPhone" varchar(50),
	"featured" boolean DEFAULT false NOT NULL,
	"expiresAt" timestamp,
	"status" "gig_status" DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    ALTER TABLE "gigs" ADD CONSTRAINT "gigs_slug_unique" UNIQUE("slug");
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create learning_resources table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "learning_resources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"type" varchar(100),
	"category" varchar(100),
	"level" varchar(50),
	"url" varchar(500),
	"provider" varchar(255),
	"cost" varchar(100),
	"duration" varchar(100),
	"tags" json,
	"featured" boolean DEFAULT false NOT NULL,
	"status" "resource_status" DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    ALTER TABLE "learning_resources" ADD CONSTRAINT "learning_resources_slug_unique" UNIQUE("slug");
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create events table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"type" varchar(100),
	"category" varchar(100),
	"startDate" timestamp NOT NULL,
	"endDate" timestamp,
	"location" varchar(255),
	"address" text,
	"latitude" varchar(50),
	"longitude" varchar(50),
	"virtual" boolean DEFAULT false NOT NULL,
	"meetingUrl" varchar(500),
	"registrationUrl" varchar(500),
	"organizer" varchar(255),
	"organizerEmail" varchar(320),
	"capacity" integer,
	"tags" json,
	"featured" boolean DEFAULT false NOT NULL,
	"status" "event_status" DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    ALTER TABLE "events" ADD CONSTRAINT "events_slug_unique" UNIQUE("slug");
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create opportunities table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "opportunities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"description" text,
	"type" varchar(100),
	"provider" varchar(255),
	"amount" varchar(100),
	"currency" varchar(10),
	"eligibility" text,
	"applicationUrl" varchar(500),
	"deadline" timestamp,
	"tags" json,
	"featured" boolean DEFAULT false NOT NULL,
	"status" "opportunity_status" DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    ALTER TABLE "opportunities" ADD CONSTRAINT "opportunities_slug_unique" UNIQUE("slug");
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create blog_posts table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "blog_posts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"excerpt" text,
	"content" text NOT NULL,
	"coverImage" varchar(500),
	"category" varchar(100),
	"tags" json,
	"authorId" integer NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"publishedAt" timestamp,
	"status" "blog_status" DEFAULT 'draft' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

DO $$ BEGIN
    ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_slug_unique" UNIQUE("slug");
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create forum_threads table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "forum_threads" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(500) NOT NULL,
	"slug" varchar(500) NOT NULL,
	"content" text NOT NULL,
	"category" "thread_category" DEFAULT 'general' NOT NULL,
	"authorId" integer,
	"authorName" varchar(255),
	"isPinned" boolean DEFAULT false NOT NULL,
	"isLocked" boolean DEFAULT false NOT NULL,
	"viewCount" integer DEFAULT 0 NOT NULL,
	"replyCount" integer DEFAULT 0 NOT NULL,
	"upvotes" integer DEFAULT 0 NOT NULL,
	"downvotes" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastActivityAt" timestamp DEFAULT now() NOT NULL
);

DO $$ BEGIN
    ALTER TABLE "forum_threads" ADD CONSTRAINT "forum_threads_slug_unique" UNIQUE("slug");
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create forum_replies table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "forum_replies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"threadId" integer NOT NULL,
	"content" text NOT NULL,
	"authorId" integer,
	"authorName" varchar(255),
	"parentReplyId" integer,
	"upvotes" integer DEFAULT 0 NOT NULL,
	"downvotes" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);

-- Create forum_votes table (only if it doesn't exist)
CREATE TABLE IF NOT EXISTS "forum_votes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"userId" integer NOT NULL,
	"targetType" "vote_target" NOT NULL,
	"targetId" integer NOT NULL,
	"voteType" "vote_type" NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);

-- Add missing columns to existing tables if they don't exist
DO $$ BEGIN
    ALTER TABLE "users" ADD COLUMN "categories" json;
EXCEPTION
    WHEN duplicate_column THEN null;
END $$;

-- Insert admin users (only if they don't exist)
INSERT INTO users ("openId", name, email, role, "loginMethod", "createdAt", "updatedAt", "lastSignedIn")
VALUES 
  ('admin-test', 'Admin User', 'admin@techatlas.ug', 'admin', 'supabase', NOW(), NOW(), NOW()),
  ('udatalabs-admin', 'UData Labs Admin', 'udatalabs@gmail.com', 'admin', 'supabase', NOW(), NOW(), NOW())
ON CONFLICT ("openId") DO NOTHING;

-- Success message
SELECT 'Tech Atlas database setup completed successfully! All tables created or updated.' as message;