CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`coverImage` varchar(500),
	`category` varchar(100),
	`tags` json,
	`authorId` int NOT NULL,
	`featured` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`status` enum('draft','pending','approved','rejected','published') NOT NULL DEFAULT 'draft',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `communities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`focusAreas` json,
	`type` varchar(100),
	`location` varchar(255),
	`memberCount` int,
	`email` varchar(320),
	`website` varchar(500),
	`slack` varchar(500),
	`discord` varchar(500),
	`telegram` varchar(500),
	`twitter` varchar(255),
	`logo` varchar(500),
	`verified` boolean NOT NULL DEFAULT false,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `communities_id` PRIMARY KEY(`id`),
	CONSTRAINT `communities_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`type` varchar(100),
	`category` varchar(100),
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`location` varchar(255),
	`address` text,
	`latitude` varchar(50),
	`longitude` varchar(50),
	`virtual` boolean NOT NULL DEFAULT false,
	`meetingUrl` varchar(500),
	`registrationUrl` varchar(500),
	`organizer` varchar(255),
	`organizerEmail` varchar(320),
	`capacity` int,
	`tags` json,
	`featured` boolean NOT NULL DEFAULT false,
	`status` enum('pending','approved','rejected','completed') NOT NULL DEFAULT 'pending',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `events_id` PRIMARY KEY(`id`),
	CONSTRAINT `events_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `gigs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`requirements` text,
	`category` varchar(100),
	`budget` int,
	`currency` varchar(10) DEFAULT 'UGX',
	`duration` varchar(100),
	`skills` json,
	`remote` boolean NOT NULL DEFAULT true,
	`location` varchar(255),
	`contactEmail` varchar(320),
	`contactPhone` varchar(50),
	`featured` boolean NOT NULL DEFAULT false,
	`expiresAt` timestamp,
	`status` enum('pending','approved','rejected','completed','expired') NOT NULL DEFAULT 'pending',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `gigs_id` PRIMARY KEY(`id`),
	CONSTRAINT `gigs_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `hubs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`focusAreas` json,
	`location` varchar(255),
	`address` text,
	`latitude` varchar(50),
	`longitude` varchar(50),
	`email` varchar(320),
	`phone` varchar(50),
	`website` varchar(500),
	`logo` varchar(500),
	`verified` boolean NOT NULL DEFAULT false,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `hubs_id` PRIMARY KEY(`id`),
	CONSTRAINT `hubs_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`company` varchar(255) NOT NULL,
	`description` text,
	`requirements` text,
	`responsibilities` text,
	`type` enum('full-time','part-time','internship','contract') NOT NULL,
	`location` varchar(255),
	`remote` boolean NOT NULL DEFAULT false,
	`skills` json,
	`experienceLevel` varchar(100),
	`salaryMin` int,
	`salaryMax` int,
	`currency` varchar(10) DEFAULT 'UGX',
	`applicationUrl` varchar(500),
	`applicationEmail` varchar(320),
	`featured` boolean NOT NULL DEFAULT false,
	`expiresAt` timestamp,
	`status` enum('pending','approved','rejected','expired') NOT NULL DEFAULT 'pending',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `jobs_id` PRIMARY KEY(`id`),
	CONSTRAINT `jobs_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `learning_resources` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`type` varchar(100),
	`category` varchar(100),
	`level` varchar(50),
	`url` varchar(500),
	`provider` varchar(255),
	`cost` varchar(100),
	`duration` varchar(100),
	`tags` json,
	`featured` boolean NOT NULL DEFAULT false,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `learning_resources_id` PRIMARY KEY(`id`),
	CONSTRAINT `learning_resources_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`type` varchar(100),
	`provider` varchar(255),
	`amount` varchar(100),
	`currency` varchar(10),
	`eligibility` text,
	`applicationUrl` varchar(500),
	`deadline` timestamp,
	`tags` json,
	`featured` boolean NOT NULL DEFAULT false,
	`status` enum('pending','approved','rejected','expired') NOT NULL DEFAULT 'pending',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `opportunities_id` PRIMARY KEY(`id`),
	CONSTRAINT `opportunities_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `startups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`industry` varchar(100),
	`focusAreas` json,
	`stage` varchar(100),
	`founded` int,
	`location` varchar(255),
	`latitude` varchar(50),
	`longitude` varchar(50),
	`teamSize` int,
	`email` varchar(320),
	`website` varchar(500),
	`twitter` varchar(255),
	`linkedin` varchar(255),
	`logo` varchar(500),
	`verified` boolean NOT NULL DEFAULT false,
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`createdBy` int NOT NULL,
	`approvedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`approvedAt` timestamp,
	CONSTRAINT `startups_id` PRIMARY KEY(`id`),
	CONSTRAINT `startups_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
ALTER TABLE `users` MODIFY COLUMN `role` enum('user','admin','moderator','editor') NOT NULL DEFAULT 'user';--> statement-breakpoint
ALTER TABLE `users` ADD `bio` text;--> statement-breakpoint
ALTER TABLE `users` ADD `skills` json;--> statement-breakpoint
ALTER TABLE `users` ADD `location` varchar(255);--> statement-breakpoint
ALTER TABLE `users` ADD `website` varchar(500);--> statement-breakpoint
ALTER TABLE `users` ADD `github` varchar(255);--> statement-breakpoint
ALTER TABLE `users` ADD `twitter` varchar(255);--> statement-breakpoint
ALTER TABLE `users` ADD `linkedin` varchar(255);