-- Fix Events Table to Match Router Exactly
-- Run this to recreate the events table with the correct structure

-- Drop the existing events table if it exists (this will remove any test data)
DROP TABLE IF EXISTS "events";

-- Create events table that matches exactly what the router sends
CREATE TABLE "events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL UNIQUE,
	"description" text,
	"type" varchar(100),
	"category" varchar(100),
	"startDate" timestamp NOT NULL,
	"endDate" timestamp,
	"location" varchar(255),
	"address" text,
	"virtual" boolean DEFAULT false NOT NULL,
	"meetingUrl" varchar(500),
	"registrationUrl" varchar(500),
	"organizer" varchar(255),
	"organizerEmail" varchar(320),
	"capacity" integer,
	"tags" json,
	"featured" boolean DEFAULT false NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"createdBy" integer NOT NULL,
	"approvedBy" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"approvedAt" timestamp
);

-- Test the table structure
SELECT 'Events table recreated successfully! Ready for submissions.' as message;