-- Tech Atlas Governance Roles Setup
-- Creates a comprehensive role-based access control system

-- Update users table to support governance roles
DO $$ BEGIN
    ALTER TABLE "users" ADD COLUMN "permissions" json;
EXCEPTION
    WHEN duplicate_column THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "users" ADD COLUMN "assignedBy" integer;
EXCEPTION
    WHEN duplicate_column THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "users" ADD COLUMN "roleAssignedAt" timestamp;
EXCEPTION
    WHEN duplicate_column THEN null;
END $$;

DO $$ BEGIN
    ALTER TABLE "users" ADD COLUMN "isActive" boolean DEFAULT true;
EXCEPTION
    WHEN duplicate_column THEN null;
END $$;

-- Create role hierarchy table
CREATE TABLE IF NOT EXISTS "role_hierarchy" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "roleName" varchar(50) NOT NULL UNIQUE,
    "displayName" varchar(100) NOT NULL,
    "description" text,
    "level" integer NOT NULL, -- Higher number = more permissions
    "permissions" json NOT NULL,
    "canAssignRoles" json, -- Array of roles this role can assign
    "createdAt" timestamp DEFAULT now() NOT NULL,
    "updatedAt" timestamp DEFAULT now() NOT NULL
);

-- Insert role hierarchy (from lowest to highest level)
INSERT INTO "role_hierarchy" ("roleName", "displayName", "description", "level", "permissions", "canAssignRoles") VALUES
('user', 'Community Member', 'Regular platform user with basic access', 1, 
 '["view_content", "submit_content", "participate_forum", "update_profile"]', 
 '[]'),

('contributor', 'Content Contributor', 'Trusted user who can submit content with less moderation', 2,
 '["view_content", "submit_content", "participate_forum", "update_profile", "fast_track_submissions"]',
 '[]'),

('moderator', 'Content Moderator', 'Moderates content and manages community discussions', 3,
 '["view_content", "submit_content", "participate_forum", "update_profile", "moderate_content", "manage_forum", "view_reports", "moderate_users"]',
 '["user", "contributor"]'),

('editor', 'Content Editor', 'Manages content quality and editorial standards', 4,
 '["view_content", "submit_content", "participate_forum", "update_profile", "moderate_content", "manage_forum", "view_reports", "moderate_users", "edit_content", "manage_categories", "feature_content"]',
 '["user", "contributor", "moderator"]'),

('admin', 'Platform Administrator', 'Full platform administration except core system management', 5,
 '["view_content", "submit_content", "participate_forum", "update_profile", "moderate_content", "manage_forum", "view_reports", "moderate_users", "edit_content", "manage_categories", "feature_content", "manage_users", "view_analytics", "manage_settings", "bulk_operations"]',
 '["user", "contributor", "moderator", "editor"]'),

('core_admin', 'Core Administrator', 'Ultimate platform control with system-level access', 6,
 '["view_content", "submit_content", "participate_forum", "update_profile", "moderate_content", "manage_forum", "view_reports", "moderate_users", "edit_content", "manage_categories", "feature_content", "manage_users", "view_analytics", "manage_settings", "bulk_operations", "manage_admins", "system_config", "database_access", "security_settings"]',
 '["user", "contributor", "moderator", "editor", "admin"]')

ON CONFLICT ("roleName") DO UPDATE SET
    "displayName" = EXCLUDED."displayName",
    "description" = EXCLUDED."description",
    "level" = EXCLUDED."level",
    "permissions" = EXCLUDED."permissions",
    "canAssignRoles" = EXCLUDED."canAssignRoles",
    "updatedAt" = now();

-- Create audit log for role changes
CREATE TABLE IF NOT EXISTS "role_audit_log" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "userId" integer NOT NULL,
    "previousRole" varchar(50),
    "newRole" varchar(50) NOT NULL,
    "assignedBy" integer NOT NULL,
    "reason" text,
    "createdAt" timestamp DEFAULT now() NOT NULL
);

-- Create moderation actions log
CREATE TABLE IF NOT EXISTS "moderation_log" (
    "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "moderatorId" integer NOT NULL,
    "action" varchar(50) NOT NULL, -- approve, reject, delete, ban, etc.
    "targetType" varchar(50) NOT NULL, -- event, job, user, thread, etc.
    "targetId" integer NOT NULL,
    "reason" text,
    "metadata" json,
    "createdAt" timestamp DEFAULT now() NOT NULL
);

-- Update existing admin users to core_admin
UPDATE users SET 
    role = 'core_admin',
    "roleAssignedAt" = now(),
    "isActive" = true
WHERE email = 'udatalabs@gmail.com' OR role = 'admin';

-- Create some sample moderators (you can modify these)
INSERT INTO users ("openId", name, email, role, "loginMethod", "roleAssignedAt", "isActive", "createdAt", "updatedAt", "lastSignedIn")
VALUES 
  ('sample-moderator-1', 'Sample Moderator', 'moderator@techatlas.ug', 'moderator', 'supabase', NOW(), true, NOW(), NOW(), NOW()),
  ('sample-editor-1', 'Sample Editor', 'editor@techatlas.ug', 'editor', 'supabase', NOW(), true, NOW(), NOW(), NOW())
ON CONFLICT ("openId") DO UPDATE SET
    role = EXCLUDED.role,
    "roleAssignedAt" = now(),
    "isActive" = true;

-- Success message
SELECT 'Governance roles setup completed! Role hierarchy established with proper permissions.' as message;