-- ============================================
-- VERIFY FORUM SETUP
-- ============================================
-- Run this in Supabase SQL Editor to check forum tables

-- ============================================
-- Check if forum_threads table exists
-- ============================================
SELECT 
    'forum_threads table' as check_name,
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM information_schema.tables 
            WHERE table_name = 'forum_threads'
        ) THEN '✅ EXISTS'
        ELSE '❌ MISSING'
    END as status;

-- ============================================
-- Check forum_threads columns
-- ============================================
SELECT 
    column_name, 
    data_type, 
    character_maximum_length,
    is_nullable,
    column_default
FROM information_schema.columns 
WHERE table_name = 'forum_threads'
ORDER BY ordinal_position;

-- ============================================
-- Check if thread_category enum exists
-- ============================================
SELECT 
    'thread_category enum' as check_name,
    CASE 
        WHEN EXISTS (
            SELECT 1 FROM pg_type 
            WHERE typname = 'thread_category'
        ) THEN '✅ EXISTS'
        ELSE '❌ MISSING'
    END as status;

-- ============================================
-- Check thread_category enum values
-- ============================================
SELECT 
    enumlabel as category_value
FROM pg_enum
WHERE enumtypid = (SELECT oid FROM pg_type WHERE typname = 'thread_category')
ORDER BY enumsortorder;

-- ============================================
-- Test insert (will be rolled back)
-- ============================================
BEGIN;

-- Try to insert a test thread
INSERT INTO forum_threads (
    title,
    slug,
    content,
    category,
    "authorId",
    "authorName"
) VALUES (
    'Test Thread',
    'test-thread-' || floor(random() * 1000000),
    'This is a test thread content.',
    'general',
    1,
    'Test User'
);

-- Check if insert worked
SELECT 
    'Test insert' as check_name,
    '✅ SUCCESS' as status,
    id,
    title,
    slug,
    category,
    "createdAt"
FROM forum_threads 
WHERE title = 'Test Thread'
ORDER BY "createdAt" DESC
LIMIT 1;

-- Rollback the test insert
ROLLBACK;

-- ============================================
-- Count existing threads
-- ============================================
SELECT 
    'Total threads' as metric,
    COUNT(*) as count
FROM forum_threads;

-- ============================================
-- Check recent threads
-- ============================================
SELECT 
    id,
    title,
    category,
    "authorName",
    "createdAt"
FROM forum_threads
ORDER BY "createdAt" DESC
LIMIT 5;

-- ============================================
-- Summary
-- ============================================
SELECT 
    'Forum Setup Status' as summary,
    CASE 
        WHEN EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'forum_threads')
        AND EXISTS (SELECT 1 FROM pg_type WHERE typname = 'thread_category')
        THEN '✅ READY'
        ELSE '❌ NEEDS SETUP'
    END as status;

-- ============================================
-- If forum_threads table is missing, run this:
-- ============================================
-- CREATE TABLE IF NOT EXISTS "forum_threads" (
--     "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     "title" varchar(500) NOT NULL,
--     "slug" varchar(500) NOT NULL,
--     "content" text NOT NULL,
--     "category" varchar(50) DEFAULT 'general' NOT NULL,
--     "authorId" integer,
--     "authorName" varchar(255),
--     "isPinned" boolean DEFAULT false NOT NULL,
--     "isLocked" boolean DEFAULT false NOT NULL,
--     "viewCount" integer DEFAULT 0 NOT NULL,
--     "replyCount" integer DEFAULT 0 NOT NULL,
--     "upvotes" integer DEFAULT 0 NOT NULL,
--     "downvotes" integer DEFAULT 0 NOT NULL,
--     "createdAt" timestamp DEFAULT now() NOT NULL,
--     "updatedAt" timestamp DEFAULT now() NOT NULL,
--     "lastActivityAt" timestamp DEFAULT now() NOT NULL,
--     CONSTRAINT "forum_threads_slug_unique" UNIQUE("slug")
-- );
